MvcCoreAdoNet/Models/Doctor.cs
namespace MvcCoreAdoNet.Models
{
    public class Doctor
    {
        public int IdHospital { get; set; }
        public int DoctorId { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        public int Salario { get; set; }
    }
}

MvcCoreAdoNet/Models/Hospital.cs
namespace MvcCoreAdoNet.Models
{
    public class Hospital
    {
        public int IdHospital { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int Camas { get; set; }
    }
}

MvcCoreAdoNet/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreAdoNet.Models;
using MvcCoreAdoNet.Repositories;

namespace MvcCoreAdoNet.Controllers
{
    public class DoctoresController : Controller
    {
        private RepositoryHospital repo;

        public DoctoresController()
        {
            this.repo = new RepositoryHospital();
        }

        public async Task<IActionResult> Index()
        {
            List<Doctor> doctores = await this.repo.GetAllDoctoresAsync();
            List<string> especialidades = await this.repo.GetEspecialidadesAsync();
            ViewData["ESPECIALIDADES"] = especialidades;
            return View(doctores);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string especialidad)
        {
            List<Doctor> doctoresFiltrados = await this.repo.GetDoctoresEspecialidadAsync(especialidad);
            List<string> especialidades = await this.repo.GetEspecialidadesAsync();
            ViewData["ESPECIALIDADES"] = especialidades;
            return View(doctoresFiltrados);
        }
    }
}

MvcCoreAdoNet/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreAdoNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Vista1()
        {
            return View();
        }
    }
}

MvcCoreAdoNet/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreAdoNet.Models;
using MvcCoreAdoNet.Repositories;

namespace MvcCoreAdoNet.Controllers
{
    public class HospitalesController : Controller
    {
        private RepositoryHospital repo;
        
        public HospitalesController()
        {
            this.repo = new RepositoryHospital();
        }
        public async Task<IActionResult> Index()
        {
            List<Hospital> hospitales = await this.repo.GetAllHospitalesAsync();
            return View(hospitales);
        }
        public async Task<IActionResult> Details(int id)
        {
            Hospital hospital = await this.repo.FindHospitalAsync(id);
            return View(hospital);
        }
        public IActionResult Create()
        {
            return View();
        }

        // EN LOS METODOS POST DE LAS VISTAS SI QUE RECIBIMOS LOS OBJETOS
        [HttpPost]
        public async Task<IActionResult> Create(Hospital hospital)
        {
            await this.repo.InsertHospitalAsync(hospital.IdHospital, hospital.Nombre,
                hospital.Direccion, hospital.Telefono, hospital.Camas);
            ViewData["MENSAJE"] = "Hospital insertado";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Hospital hospital =
                await this.repo.FindHospitalAsync(id);
            return View(hospital);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Hospital hospital)
        {
            await this.repo.UpdateHospitalAsync(hospital.IdHospital, hospital.Nombre, hospital.Direccion,
                hospital.Telefono, hospital.Camas);
            ViewData["MENSAJE"] = "Hospital modificado";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.repo.DeleteHospitalAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreAdoNet/Views/Doctores/Index.cshtml
@model List<Doctor>
@{
    List<string> especialidades = (List<string>)ViewData["ESPECIALIDADES"];
}

<h1>DOCTORES</h1>

<form method="post">
    <label>Introduzca especialidad: </label>
    <select name="especialidad" class="form-control">
        @foreach (string espe in especialidades)
            {
                <option>@espe</option>
            }
        </select>
    <button class="btn btn-primary">Cargar doctores</button>
</form>

<table class="table-striped">
    <thead>
        <tr>
            <th>HOSPITAL_COD</th>
            <th>DOCTOR_NO</th>
            <th>APELLIDO</th>
            <th>ESPECIALIDAD</th>
            <th>SALARIO</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Doctor doctor in Model)
        {
            <tr>
                <td>@doctor.IdHospital</td>
                <td>@doctor.DoctorId</td>
                <td>@doctor.Apellido</td>
                <td>@doctor.Especialidad</td>
                <td>@doctor.Salario</td>
            </tr>
        }
    </tbody>
</table>

MvcCoreAdoNet/Views/Home/Index.cshtml
<h1 style="color:darkviolet">
    INDEX
</h1>
<button id="botonVista" class="btn btn-info">Cambiar mensaje layout</button>

@section scripts {
    <script>
        $(document).ready(function() {
            $("#botonVista").click(function() {
                $("#mensajeVista").text("Mensaje cambiado")
            })
        })
    </script>
}

MvcCoreAdoNet/Views/Home/Vista1.cshtml
<h1>
    VISTA 1
</h1>

@section images {
    <img src="~/images/tres.jpg"/>
}

MvcCoreAdoNet/Views/Hospitales/Create.cshtml
<a asp-controller="Hospitales" asp-action="Index">Volver al menu</a>

<h1>
    Crear Hospitales
</h1>

<form method="post">
    <label>Id</label>
    <input type="number" name="idhospital" class="form-control"/><br />
    <label>Nombre</label>
    <input type="text" name="nombre" class="form-control" /><br />
     <label>Direccion</label>
    <input type="text" name="direccion" class="form-control"/><br />
    <label>Telefono</label>
    <input type="text" name="telefono" class="form-control" /><br />
    <label>Camas</label>
    <input type="number" name="camas" class="form-control" /><br />
    <button class="btn btn-primary">Insertar</button>
</form>

<h2 style="color:blueviolet">
    @ViewData["MENSAJE"]
</h2>

MvcCoreAdoNet/Views/Hospitales/Details.cshtml
@model Hospital

<h1>Detalles</h1>

<a asp-controller="Hospitales" asp-action="Index">Back to List</a>

<ul class="list-group">
    <li class="list-group-item">
        ID: @Model.IdHospital
    </li>
    <li class="list-group-item">
        Nombre: @Model.Nombre
    </li>
    <li class="list-group-item">
        Dirección: @Model.Direccion
    </li>
    <li class="list-group-item">
        Teléfono: @Model.Telefono
    </li>
    <li class="list-group-item">
        Camas: @Model.Camas
    </li>
</ul>

MvcCoreAdoNet/Views/Hospitales/Edit.cshtml
@model Hospital

<a asp-controller="Hospitales" asp-action="Index">Volver al menu</a>

<h1>
    Editar hospital
</h1>

@if (Model != null)
{
    <form method="post">
        <label>Id</label>
        <input type="number" name="idhospital" class="form-control" value="@Model.IdHospital" readonly/><br />
        <label>Nombre</label>
        <input type="text" name="nombre" class="form-control" value="@Model.Nombre" /><br />
        <label>Direccion</label>
        <input type="text" name="direccion" class="form-control" value="@Model.Direccion" /><br />
        <label>Telefono</label>
        <input type="text" name="telefono" class="form-control" value="@Model.Telefono" /><br />
        <label>Camas</label>
        <input type="number" name="camas" class="form-control" value="@Model.Camas" /><br />
        <button class="btn btn-info text-white">Editar</button>
    </form>
}

<h2 style="color: fuchsia">
    @ViewData["MENSAJE"]
</h2>

MvcCoreAdoNet/Views/Hospitales/Index.cshtml
@model List<Hospital>

<h1 class="text-primary">Hospitales INDEX</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Teléfono</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Hospital hospital in Model)
        {
            <tr>
                <td>@hospital.Nombre</td>
                <td>@hospital.Direccion</td>
                <td>@hospital.Telefono</td>
                <td>
                    <a class="btn btn-info" asp-controller="Hospitales" asp-action="Details" asp-route-id="@hospital.IdHospital">Detalles</a>
                    <a class="btn btn-warning" asp-controller="Hospitales" asp-action="Edit" asp-route-id="@hospital.IdHospital">Update</a>
                    <a class="btn btn-danger" asp-controller="Hospitales" asp-action="Delete" asp-route-id="@hospital.IdHospital">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.ActionLink("Crear hospital", "Create", "Hospitales")

MvcCoreAdoNet/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Plantilla</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/carousel.css" rel="stylesheet">
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Vista1" class="nav-link">Vista 1</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Hospitales" asp-action="Index" class="nav-link">Hospitales</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Doctores" asp-action="Index" class="nav-link">Doctores</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main role="main">

        <div class="mt-5">
            @if(IsSectionDefined("images"))
            {
                @RenderSection("images", false)
            } else
            {
                <img src="~/images/cuatro.png" width="100"/>
            }
            <img src="~/images/dos.webp" />
            <h1>ZONA DE VISTAS</h1>
            <p id="mensajeVista">Mensaje a cambiar</p>
            @RenderBody()
        </div>

        <!-- Marketing messaging and featurettes
        ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery-4.0.0.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    @RenderSection("scripts", false)
</body>
</html>